services:

  postgres:
    image: postgres:15
    container_name: projeto-db-postgres
    environment:
      POSTGRES_DB: shopdb
      POSTGRES_USER: shopuser
      POSTGRES_PASSWORD: shoppass
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  mongo:
    image: mongo:6
    container_name: projeto-db-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data

  neo4j:
    image: neo4j:5
    container_name: projeto-db-neo4j
    environment:
      NEO4J_AUTH: neo4j/neo4jpass
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

  redis:
    image: redis:7
    container_name: projeto-db-redis
    ports:
      - "6379:6379"

  api:
    build: ./api
    container_name: projeto-db-api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - mongo
      - neo4j
      - redis
    environment:
      # ðŸ”¥ POSTGRES (corrigido)
      POSTGRES_HOST: postgres
      POSTGRES_DB: shopdb
      POSTGRES_USER: shopuser
      POSTGRES_PASSWORD: shoppass

      # Mongo
      MONGO_URI: mongodb://mongo:27017/shop

      # Neo4j
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: neo4jpass

      # Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379

volumes:
  neo4j_data:
